runtime: php
env: flex
runtime_config:
  document_root: public
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7
  cpu_utilization:
    target_utilization: 0.8
env_variables:
  # Put production environment variables here.
  APP_NAME: Formula
  APP_LOG: errorlog
  APP_KEY: base64:vA6NpNXmJUR4Qoh0mhNit+oKBqe/xcsFi1lu03oRWrg=
  APP_DEBUG: false
  DB_CONNECTION: mysql
  DB_HOST: 34.95.147.151
  DB_PORT: 3306
  DB_DATABASE: formula_pr
  DB_USERNAME: usuario
  DB_PASSWORD: 46302113&Gcloud