runtime: php
env: flex
runtime_config:
  document_root: public
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 19
  cpu_utilization:
    target_utilization: 0.8
env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:vA6NpNXmJUR4Qoh0mhNit+oKBqe/xcsFi1lu03oRWrg=